---

- set_fact:
    app_dir: "{{ local_home }}/.local/bin"
    symlink_dir: "{{ local_home }}/Apps"
    filename: -cryptomator.AppImage
    repo: "https://api.github.com/repos/cryptomator/cryptomator/releases/latest"

- name: "find what does exsists in {{ app_dir }}"
  find:
    paths: "{{ app_dir }}"
    patterns: "*{{ filename }}"
  register: cryptomator_app

- name: download cryptomator 
  block:
    - name: get cryptomator url from latest github
      shell: curl -s {{ repo }} | grep 'browser_download_url.*AppImage"' \ | cut -d ':' -f 2,3 \ | tr -d \"
      register: url
      args:
        warn: no

    - set_fact:
        url_clean: "{{ url.stdout }}"
        appname: "{{ url.stdout | basename }}"

    - set_fact:
        version: "{{ appname | regex_findall('-(.*)-') | first }}"
    
    - name: Download latest Cryptomator AppImage
      get_url:
        url: "{{ url_clean }}"
        dest: "{{ app_dir }}/{{ version }}{{ filename }}"
        mode: a+x
    - set_fact:
        written_file: "{{ app_dir }}/{{ version }}{{ filename }}"
    
    - name: Create symlink
      file:
        src: "{{ written_file }}"
        dest: "{{ symlink_dir }}/cryptomator.AppImage"
        state: link

  when: cryptomator_app.matched == 0


# https://stackoverflow.com/questions/35984151/how-to-create-new-system-service-by-ansible-playbook
