---
# tasks file for /home/kevinjel/fresh_pop/roles/dconf-settings

- name: Configure Gnome extensions
  dconf:
    key: "/org/gnome/shell/extensions/{{ item.description }}"
    value: "{{ item.value | string }}"
    state: present
  loop:
    - { description: 'pop-shell/focus-up', value: "{{ blank }}" }
    - { description: 'pop-shell/focus-down', value: "{{ blank }}" }
    - { description: 'pop-shell/toggle-floating', value: "{{ blank }}" }
    - { description: 'pop-shell/tile-by-default', value: 'true' }

- name: Configure Gnome interfaces
  dconf:
    key: "/org/gnome/desktop/interface/{{ item.description }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { description: 'show-battery-percentage', value: 'true' }
    - { description: 'clock-show-weekday', value: 'true' }
    - { description: 'clock-format', value: '"24h"' }


- name: Configure Gnome WM keybindings
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/{{ item.description }}"
    value: "{{ item.value | string }}"
    state: present
  loop:
    - { description: 'switch-to-workspace-up', value: "['<Super>k']" }
    - { description: 'switch-to-workspace-down', value: "['<Super>j']" }
    - { description: 'move-to-workspace-1', value: "['<Super>1']" }
    - { description: 'move-to-workspace-2', value: "['<Super>2']" }
    - { description: 'move-to-workspace-3', value: "['<Super>3']" }
    - { description: 'move-to-workspace-4', value: "['<Super>4']" }
    - { description: 'toggle-fullscreen', value: "['<Shift><Super>f']" }
    - { description: 'maximize', value: "['<Super>f']" }

- name: Configure keyboard remaps
  dconf:
    key: "/org/gnome/desktop/input-sources/{{ item.description }}"
    value: "{{ item.value | string }}"
    state: present
  loop:
    - { description: 'xkb-options', value: "['caps:escape']" }


- name: Configure Gnome keybindings
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/{{ item.description }}"
    value: "{{ item.value | string }}"
    state: present
  loop:
    - { description: 'home', value: "['<Super>d']" }
    - { description: 'email', value: "{{ blank }}" }
    - { description: 'terminal', value: "['<Super>Return']" }
    - { description: 'tile-enter', value: "{{ blank }}" }
    - { description: 'www', value: "['<Shift><Super>Return']" }
    - { description: 'volume-up', value: "['AudioRaiseVolume']" }
    - { description: 'volume-down', value: "['AudioLowerVolume']" }
    - { description: 'volume-mute', value: "['AudioMute']" }
    - { description: 'play', value: "['AudioPlay']" }
    - { description: 'stop', value: "{{ blank }}" }
    - { description: 'next', value: "['AudioNext']" }
    - { description: 'previous', value: "['AudioPrev']" }
    - { description: 'screencast', value: "{{ blank }}" }
    
- name: Configure locale format
  dconf:
    key: "/system/locale/region"
    value: "'nl_NL.UTF-8'"
    state: present

- name: Change touchpad speed
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/speed"
    value: "0.18382352941176472"
    state: present

