---

- name: Install apt packages
  become: yes
  apt:
    pkg:
    - snapd
    - bat
    - fzf
    - htop
    - thefuck
    - neovim
    - tmux
    - tree
    - alacritty
    - zsh
    - appmenu-gtk3-module
    - gnome-tweaks

- name: Remove apt packages
  become: yes
  apt:
    name: kdeconnect 
    state: absent

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes
