---
- name: Install apt packages
  become: yes
  apt:
    pkg:
      - scrot
      - autoconf
      - automake 
      - g++ 
      - gcc 
      - libpng-dev
      - libpoppler-dev
      - libpoppler-glib-dev
      - libz-dev
      - make
      - pkg-config
      - pandoc
      - snapd
      - fzf
      - htop
      - thefuck
      - neovim
      - tmux
      - tree
      - alacritty
      - zsh
      - appmenu-gtk3-module
      - gnome-tweaks
      - tlp
      - network-manager-l2tp
      - network-manager-l2tp-gnome
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - yubikey-manager
      - yubikey-personalization
      - qemu-kvm
      - libvirt-clients
      - libvirt-daemon-system
      - bridge-utils
      - virt-manager
      - libvirt-daemon
      - ovmf
      - gnome-boxes
      - nextcloud-desktop
      - neovim
      - ranger
      - ripgrep
      - fd-find
      - universal-ctags
      - ttf-mscorefonts-installer
      - alacritty
      - silversearcher-ag
      - xsel
      - libx11-dev
      - mesa-common-dev
      - libglu1-mesa-dev
      - libxrandr-dev
      - libxi-dev
      - borgbackup
      - yadm
      - python3
      - python3-pip
      - syncthing
      - brave-browser
      - flameshot
      - graphviz
      - jq
        #Tasks found here : https://github.com/Dalee/ansible.install-nodejs
- name: Checking node install
  shell: node --version | sed -e 's/^v14.*$/14/'
  register: node_version
  ignore_errors: true
  changed_when: false

- name: Adding repository for node 14
  shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
  when: node_version.stdout is not search('14')

- name: Install node
  apt: name=nodejs state=present

- name: Checking yarn installation
  shell: yarn --version
  register: yarn_installed
  ignore_errors: true
  changed_when: false

- name: Adding yarn repository key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
  when: yarn_installed.rc != 0

- name: Adding postgresql repository
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
  when: yarn_installed.rc != 0

- name: Adding yarn
  apt:
    name: yarn

- name: neovim-remote
  shell: pip3 install neovim-remote

- name: pyvim
  shell: pip3 install pynvim

- name: install ueberzug
  become: yes
  shell: pip3 install ueberzug

- name: change mirror us > de
  become: yes
  shell: sed -i 's/us./de./' /etc/apt/sources.list

- name: neovim
  become: yes
  shell: npm i -g neovim

- name: Remove apt packages
  become: yes
  apt:
    name:
      ["falkon", "kdeconnect", "midori", "fonts-powerline", "kazam", "xl2tpd"]
    state: absent

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes
