---
# tasks file for /home/kevinjel/fresh_pop/roles/gui_apps
# TODO: add the names + packages to the vars file

- name: add several flatpak items
  flatpak:
    name: "{{ item.url }}"
    state: present
    method: user
  loop:
    - { name: 'Spotify', url: 'https://flathub.org/repo/appstream/com.spotify.Client.flatpakref' }
    - { name: 'DBeaver', url: 'https://flathub.org/repo/appstream/io.dbeaver.DBeaverCommunity.flatpakref' }    
    - { name: 'Teams', url: 'https://flathub.org/repo/appstream/com.microsoft.Teams.flatpakref' }
    - { name: 'Slack', url: 'https://flathub.org/repo/appstream/com.slack.Slack.flatpakref' }
    - { name: 'Remmina', url: 'https://flathub.org/repo/appstream/org.remmina.Remmina.flatpakref' }

# - name: remove several flatpak items
#   flatpak:
#     name: "{{ item.url }}"
#     state: absent
#     method: user
#   loop:
#     - { name: 'Dropbox', url: 'https://flathub.org/repo/appstream/com.dropbox.Client.flatpakref' }

- name: add several snap items with --classic tag
  become: yes
  snap:
    name: "{{ item }}"
    classic: yes
  loop:
    - code
    - go

- name: Install snap packages
  become: yes
  snap:
    name:
      - docker
      - p3x-redis-ui
      - yubioath-desktop
