---
# tasks file for /home/kevinjel/fresh_pop/roles/gui_apps
# TODO: add the names + packages to the vars file

- name: add several flatpak items
  flatpak:
    name: "{{ item.url }}"
    state: present
    method: user
  loop:
    - {
        name: "Spotify",
        url: "https://flathub.org/repo/appstream/com.spotify.Client.flatpakref",
      }
    - {
        name: "Teams",
        url: "https://flathub.org/repo/appstream/com.microsoft.Teams.flatpakref",
      }
    - {
        name: "Slack",
        url: "https://flathub.org/repo/appstream/com.slack.Slack.flatpakref",
      }
    - {
        name: "Remmina",
        url: "https://flathub.org/repo/appstream/org.remmina.Remmina.flatpakref",
      }
    - {
        name: "Flowblade",
        url: "https://flathub.org/repo/appstream/io.github.jliljebl.Flowblade.flatpakref",
      }
    - {
        name: "Exodus",
        url: "https://flathub.org/repo/appstream/io.exodus.Exodus.flatpakref",
      }
    - {
        name: "Planner",
        url: "https://flathub.org/repo/appstream/com.github.alainm23.planner.flatpakref",
      }
    - {
        name: "Steam",
        url: "https://flathub.org/repo/appstream/com.valvesoftware.Steam.flatpakref",
      }
    - {
        name: "Gimp",
        url: "https://flathub.org/repo/appstream/org.gimp.GIMP.flatpakref",
      }
    - {
        name: "Signal",
        url: "https://dl.flathub.org/repo/appstream/org.signal.Signal.flatpakref",
      }
    - {
        name: "Nextcloud",
        url: "https://https://dl.flathub.org/repo/appstream/com.nextcloud.desktopclient.nextcloud.flatpakref",
      }

    - {
        name: "Digikam",
        url: "https://flathub.org/repo/appstream/org.kde.digikam.flatpakref",
      }
    - {
        name: "Kdenlive",
        url: "https://flathub.org/repo/appstream/org.kde.kdenlive.flatpakref",
      }

- name: remove several flatpak items
  flatpak:
    name: "{{ item.url }}"
    state: absent
    method: user
  loop:
    - {
        name: "Visual Studio Code - OSS",
        url: "https://flathub.org/repo/appstream/com.visualstudio.code.oss.flatpakref",
      }

- name: add several snap items with --classic tag
  become: yes
  snap:
    name: "{{ item }}"
    classic: yes
  loop:
    - go
    - code

- name: Install snap packages
  become: yes
  snap:
    name:
      - docker
      - p3x-redis-ui
      - yubioath-desktop
      - vlc
      - pdfmixtool
      - okular

- name: remove a snap package
  become: yes
  snap:
    name:
      - auto-cpufreq
      - codium
    state: absent
