---
- set_fact:
    tempdir: /var/tmp/pline_fonts
    download: "{{ local_home }}/Download"

- name: install powerline fonts
  git:
    repo: https://github.com/powerline/fonts.git
    depth: 1
    dest: "{{ tempdir }}"

- name: Download JetBrains Mono font
  unarchive:
    src: https://download.jetbrains.com/fonts/JetBrainsMono-1.0.0.zip
    dest: /home/{{ bash_username }}/.local/share/fonts
    remote_src: yes
  become_user: "{{ bash_username }}"
  when: jetbrains_mono_file.stat.exists == False

- name: Download Nerd JetBrains Mono font
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip
    dest: /home/{{ bash_username }}/.local/share/fonts
    remote_src: yes
  become_user: "{{ bash_username }}"
  when: jetbrains_mono_file.stat.exists == False

- name: run the installer
  shell:
    cmd: "./install.sh && fc-cache -vf"
    chdir: "{{ tempdir }}"
