---

- git:
    repo: git@github.com:Afrikantahti/nvim.git
    dest:  "/home/{{ local_user }}/.config/nvim" 

- git:
    repo: git@github.com:romkatv/powerlevel10k.git 
    dest:  "/home/{{ local_user }}/powerlevel10k" 


- git:
    repo: git@github.com:zsh-users/zsh-history-substring-search.git  
    dest:  "/home/{{ local_user }}/git/zsh-history-substring-search" 
    
- name: get my dot fileee
  shell: yadm clone https://github.com/Afrikantahti/dotfiles


