---
- name: Add Typora apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: BA300B7755AFCFAE

- name: Add Typora repository
  apt_repository:
    repo: 'deb https://typora.io/linux ./'
    state: present

- name: Install Typora
  become: yes
  apt:
    pkg: typora
    state: latest
    update_cache: yes

- name: Adding lazygit
  apt_repository:
    repo: ppa:lazygit-team/release

- name: install lazygit
  apt:
    name: lazygit

- name: zerotier
  shell: curl -s https://install.zerotier.com | sudo bash

- name: install zerotier
  apt:
    name: zerotier-one

- name: "apt | ensure Google linux signing key present"
  become: yes
  become_user: root
  apt_key: 
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
    
- name: "apt | ensure Google chrome repo present"
  become: yes
  become_user: root
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: "google-chrome"
    state: present
    update_cache: yes

- name: "apt | ensure Google chrome present"
  become: yes
  become_user: root
  apt:
    name: google-chrome-stable
    state: present

